// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZma0p6oJWg5Bu0N0Vg2eFFBIKm4FbSxQ',
    appId: '1:758594392187:web:19ad57f4b117d6869292de',
    messagingSenderId: '758594392187',
    projectId: 'suremove-6a84a',
    authDomain: 'suremove-6a84a.firebaseapp.com',
    storageBucket: 'suremove-6a84a.appspot.com',
    measurementId: 'G-YSWLPDLH7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjO1j6SqvzacV7EYwqAWSc7K018D3Y1J0',
    appId: '1:758594392187:android:8bce8d0a8692658f9292de',
    messagingSenderId: '758594392187',
    projectId: 'suremove-6a84a',
    storageBucket: 'suremove-6a84a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWIOuXTeR_Gf4AU4WXAblUdiFJYdtfRv8',
    appId: '1:758594392187:ios:5bd43d1d33cc16c89292de',
    messagingSenderId: '758594392187',
    projectId: 'suremove-6a84a',
    storageBucket: 'suremove-6a84a.appspot.com',
    iosClientId: '758594392187-pdo6u3qbc60rpp40ktl9g58207imvi7t.apps.googleusercontent.com',
    iosBundleId: 'com.example.sureMove',
  );
}
